/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (number 62), U7[4]/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB17 (number 63), U10[1]/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB1 (number 54), U13[11]/RMII0_MDC
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RMII0_MDC_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RMII0_MDC_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RMII0_MDC_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTB0 (number 53), U13[10]/RMII0_MDIO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RMII0_MDIO_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RMII0_MDIO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RMII0_MDIO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTA12 (number 42), U13[12]/RMII0_RXD_1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RMII0_RXD1_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RMII0_RXD1_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RMII0_RXD1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA13 (number 43), U13[13]/RMII0_RXD_0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RMII0_RXD0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RMII0_RXD0_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RMII0_RXD0_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA14 (number 44), U13[15]/RMII0_CRS_DV
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RMII0_CRS_DV_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RMII0_CRS_DV_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RMII0_CRS_DV_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTA15 (number 45), U13[19]/RMII0_TXEN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RMII0_TXEN_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RMII0_TXEN_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RMII0_TXEN_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA17 (number 47), U13[21]/RMII0_TXD1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RMII0_TXD1_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RMII0_TXD1_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RMII0_TXD1_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA16 (number 46), U13[20]/RMII0_TXD0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RMII0_TXD0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RMII0_TXD0_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RMII0_TXD0_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA5 (number 39), U13[17]/RMII0_RXER
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RMII0_RXER_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RMII0_RXER_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RMII0_RXER_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTC16 (number 90), J1[2]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TMR_1588_0_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TMR_1588_0_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TMR_1588_0_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTC17 (number 91), J1[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TMR_1588_1_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TMR_1588_1_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TMR_1588_1_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTB22 (number 68), D12[1]/LEDRGB_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_RED_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE26 (number 33), J2[1]/D12[4]/LEDRGB_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB21 (number 67), D12[3]/LEDRGB_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BLUE_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
